---
output: html_document
---
###### IODS - Introduction to Open Data Science - 2017

# Week 5:
## Dimensionality reduction techniques

```{r}
human <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/human2.txt", header=TRUE, sep=",")
str(human)
dim(human)
```


```{r}
library(GGally); library(corrplot); library(tidyr)
ggpairs(human)
summary(human)
corrplot(cor(human))
```


```{r}
pca_human <- prcomp(human)
biplot(pca_human, choices=1:2)
```


```{r}
human_std <- scale(human)
summary(human_std)
pca_human_std <- prcomp(human_std)
biplot(pca_human_std, choices=1:2)

names(human_std)
names(pca_human_std)
```

```{r}
library(FactoMineR); library(ggplot2); library(dplyr)
data("tea")
#tea <- read.table("http://factominer.free.fr/book/tea.csv", header=T, sep=",", dec=".")
str(tea)
dim(tea)
summary(tea)
ggpairs(tea)
gather(tea) %>% ggplot(aes(value)) + facet_wrap("key", scales = "free") + geom_bar() + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))
```

